# Generated by Django 5.2 on 2025-04-27 05:42

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_calendarevent_time_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='InventoryItem',
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 4, 27, 5, 42, 27, 702836, tzinfo=datetime.timezone.utc)),
        ),
    ]
